# Generated by Django 5.2 on 2026-08-24 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_permission_category_codenames(apps, schema_editor):
    """Give pre-existing rows a unique codename derived from their name."""
    PermissionCategory = apps.get_model("user", "PermissionCategory")

    taken = set()
    for category in PermissionCategory.objects.filter(codename="").order_by("pk"):
        base = slugify(category.name).replace("-", "_").upper()[:90] or "CATEGORY"
        codename = base
        suffix = 1
        while codename in taken or (
            PermissionCategory.objects.filter(codename=codename).exclude(pk=category.pk).exists()
        ):
            codename = f"{base}_{suffix}"
            suffix += 1
        taken.add(codename)
        category.codename = codename
        category.save(update_fields=["codename"])


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_historicalmainmodule_historicalpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "ordering": ("name",),
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AddField(
            model_name="historicalmainmodule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalpermission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalpermissioncategory",
            name="codename",
            field=models.CharField(
                db_index=True, default="", max_length=100, verbose_name="codename"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpermissioncategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mainmodule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        # Added in three steps so the migration is safe on a schema that
        # already holds permission categories: the column arrives without the
        # unique index, existing rows are given a derived codename, and only
        # then is uniqueness enforced.
        migrations.AddField(
            model_name="permissioncategory",
            name="codename",
            field=models.CharField(default="", max_length=100, verbose_name="codename"),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_permission_category_codenames,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="permissioncategory",
            name="codename",
            field=models.CharField(max_length=100, unique=True, verbose_name="codename"),
        ),
        migrations.AddField(
            model_name="permissioncategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicaluserrole",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Last user to modify this row; empty until the first update.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to modify this row; empty until the first update.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
