# Generated by Django 5.2 on 2026-08-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_historicaluser_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="alternate_phone_no",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="alternate phone number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="alternate_phone_no",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="alternate phone number"
            ),
        ),
    ]
