# Generated by Django 5.2 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_seed_academic_calendar_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=302, verbose_name="full name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=302, verbose_name="full name"
            ),
        ),
    ]
