# Generated by Django 5.2 on 2026-08-24 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as deleted. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(max_length=20, verbose_name="roll number"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="University registration number, where one has been issued.",
                        max_length=30,
                        verbose_name="registration number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="middle name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("RATHER_NOT_TO_SAY", "Rather Not To Say"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "phone_no",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="phone number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STUDYING", "Studying"),
                            ("GRADUATED", "Graduated"),
                            ("DROPPED_OUT", "Dropped Out"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="STUDYING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Admission cohort. Program and department follow from it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academics.batch",
                        verbose_name="batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user to modify this row; empty until the first update.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ("batch", "roll_number"),
            },
        ),
        migrations.CreateModel(
            name="SemesterEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as deleted. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "batch_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.batchsemester",
                        verbose_name="batch semester",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user to modify this row; empty until the first update.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_enrollments",
                        to="students.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "semester enrollment",
                "verbose_name_plural": "semester enrollments",
                "ordering": ("student", "batch_semester"),
            },
        ),
        migrations.CreateModel(
            name="SubjectEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as deleted. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "is_retake",
                    models.BooleanField(
                        default=False,
                        help_text="Student is repeating this subject from an earlier semester.",
                        verbose_name="retake",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.subjectallocation",
                        verbose_name="allocation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="students.student",
                        verbose_name="student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user to modify this row; empty until the first update.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subject enrollment",
                "verbose_name_plural": "subject enrollments",
                "ordering": ("allocation", "student"),
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["batch", "status"], name="students_st_batch_i_971a42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("batch", "roll_number"),
                name="unique_active_roll_number_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_archived", False),
                    models.Q(("registration_number", ""), _negated=True),
                ),
                fields=("registration_number",),
                name="unique_active_student_registration_number",
            ),
        ),
        migrations.AddIndex(
            model_name="semesterenrollment",
            index=models.Index(
                fields=["batch_semester", "status"],
                name="students_se_batch_s_2c7251_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="semesterenrollment",
            index=models.Index(
                fields=["student"], name="students_se_student_7fcfb2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="semesterenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("student", "batch_semester"),
                name="unique_active_enrollment_per_student_semester",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["allocation"], name="students_su_allocat_c34d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["student"], name="students_su_student_4bfd8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("student", "allocation"),
                name="unique_active_enrollment_per_student_allocation",
            ),
        ),
    ]
