# Generated by Django 5.2 on 2026-08-24 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_constraint_messages"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="semesterenrollment",
            name="unique_active_enrollment_per_student_semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("student", "batch_semester"),
                name="unique_active_enrollment_per_student_semester",
                violation_error_message="That student is already enrolled in this semester.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="student",
            name="unique_active_roll_number_per_batch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("batch", "roll_number"),
                name="unique_active_roll_number_per_batch",
                violation_error_message="That roll number is already taken in this batch.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="student",
            name="unique_active_student_registration_number",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_archived", False),
                    models.Q(("registration_number", ""), _negated=True),
                ),
                fields=("registration_number",),
                name="unique_active_student_registration_number",
                violation_error_message="Another student already has that registration number.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="subjectenrollment",
            name="unique_active_enrollment_per_student_allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("student", "allocation"),
                name="unique_active_enrollment_per_student_allocation",
                violation_error_message="That student is already registered on this class.",
            ),
        ),
    ]
