# Generated by Django 5.2 on 2026-08-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_historicalsemesterenrollment_historicalstudent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudent",
            name="alternate_phone_no",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="alternate phone number"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="alternate_phone_no",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="alternate phone number"
            ),
        ),
    ]
