# Generated by Django 5.2 on 2026-09-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_alter_batchsemester_batch_and_more"),
        ("students", "0005_historicalstudent_alternate_phone_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semesterenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semester_enrollments",
                to="students.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="subjectenrollment",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academics.subjectallocation",
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="subjectenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_enrollments",
                to="students.student",
                verbose_name="student",
            ),
        ),
    ]
