# Generated by Django 5.2 on 2026-09-02 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_semesterenrollment_student_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semesterenrollment",
            options={
                "ordering": (
                    "student__first_name",
                    "student__middle_name",
                    "student__last_name",
                    "batch_semester",
                    "id",
                ),
                "verbose_name": "semester enrollment",
                "verbose_name_plural": "semester enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ("first_name", "middle_name", "last_name", "id"),
                "verbose_name": "student",
                "verbose_name_plural": "students",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectenrollment",
            options={
                "ordering": (
                    "allocation",
                    "student__first_name",
                    "student__middle_name",
                    "student__last_name",
                    "id",
                ),
                "verbose_name": "subject enrollment",
                "verbose_name_plural": "subject enrollments",
            },
        ),
    ]
