# Generated by Django 5.2 on 2026-09-05 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_academiccalendarconfiguration_and_more"),
        ("students", "0008_historicalstudentportalconfiguration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudent",
            name="graduated_by_batch",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="student",
            name="graduated_by_batch",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("graduated_by_batch", False),
                    ("status", "GRADUATED"),
                    _connector="OR",
                ),
                name="student_batch_graduation_requires_graduated",
            ),
        ),
    ]
