# Generated by Django 5.2 on 2026-08-24 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_constraint_messages"),
        ("performance", "0001_initial"),
        ("students", "0002_constraint_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="assignment",
            name="unique_active_assignment_title_per_allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("allocation", "title"),
                name="unique_active_assignment_title_per_allocation",
                violation_error_message="This class already has an assignment with that title.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="assignment",
            name="assignment_due_after_assigned",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("assigned_date")),
                    _connector="OR",
                ),
                name="assignment_due_after_assigned",
                violation_error_message="The due date cannot fall before the assigned date.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="assignmentsubmission",
            name="unique_active_submission_per_assignment_student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("assignment", "enrollment"),
                name="unique_active_submission_per_assignment_student",
                violation_error_message="That student already has a status for this assignment.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="attendancerecord",
            name="unique_active_attendance_per_session_student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("session", "enrollment"),
                name="unique_active_attendance_per_session_student",
                violation_error_message="That student is already marked for this class.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="attendancesession",
            name="unique_active_session_per_allocation_date",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("allocation", "date", "period"),
                name="unique_active_session_per_allocation_date",
                violation_error_message="Attendance for that date and period is already recorded.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="attendancesession",
            name="attendance_session_period_positive",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__gte", 1)),
                name="attendance_session_period_positive",
                violation_error_message="The class period must be 1 or more.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexam",
            name="unique_active_exam_title_per_allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("allocation", "title"),
                name="unique_active_exam_title_per_allocation",
                violation_error_message="This class already has an exam with that title.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexam",
            name="internal_exam_full_marks_positive",
            constraint=models.CheckConstraint(
                condition=models.Q(("full_marks__gt", 0)),
                name="internal_exam_full_marks_positive",
                violation_error_message="Full marks must be greater than zero.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexam",
            name="internal_exam_pass_marks_within_full",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pass_marks__isnull", True),
                    ("pass_marks__lte", models.F("full_marks")),
                    _connector="OR",
                ),
                name="internal_exam_pass_marks_within_full",
                violation_error_message="Pass marks cannot exceed full marks.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexammark",
            name="unique_active_mark_per_exam_student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("exam", "enrollment"),
                name="unique_active_mark_per_exam_student",
                violation_error_message="That student already has a mark for this exam.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexammark",
            name="internal_mark_not_negative",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("marks_obtained__isnull", True),
                    ("marks_obtained__gte", 0),
                    _connector="OR",
                ),
                name="internal_mark_not_negative",
                violation_error_message="Marks cannot be negative.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="internalexammark",
            name="internal_mark_absent_has_no_score",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_absent", False),
                    ("marks_obtained__isnull", True),
                    _connector="OR",
                ),
                name="internal_mark_absent_has_no_score",
                violation_error_message="A student marked absent cannot also have marks.",
            ),
        ),
    ]
