# Generated by Django 5.2 on 2026-08-30 13:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_historicalperformanceweightconfiguration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperformanceweightconfiguration",
            name="attendance_eligibility_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("75.00"),
                help_text="Minimum attendance percentage a student must hold to count as eligible.",
                max_digits=5,
                verbose_name="attendance eligibility threshold",
            ),
        ),
        migrations.AddField(
            model_name="performanceweightconfiguration",
            name="attendance_eligibility_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("75.00"),
                help_text="Minimum attendance percentage a student must hold to count as eligible.",
                max_digits=5,
                verbose_name="attendance eligibility threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="performanceweightconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attendance_eligibility_threshold__gte", 0),
                    ("attendance_eligibility_threshold__lte", 100),
                ),
                name="attendance_eligibility_threshold_between_0_and_100",
                violation_error_message="The attendance requirement must be between 0 and 100 percent.",
            ),
        ),
    ]
