# Generated by Django 5.2 on 2026-09-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_alter_batchsemester_batch_and_more"),
        ("performance", "0006_attendance_eligibility_threshold"),
        ("students", "0006_alter_semesterenrollment_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="academics.subjectallocation",
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="performance.assignment",
                verbose_name="assignment",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_submissions",
                to="students.subjectenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="students.subjectenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="performance.attendancesession",
                verbose_name="session",
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_sessions",
                to="academics.subjectallocation",
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="classperformancerating",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_performance_ratings",
                to="students.subjectenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="internalexam",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internal_exams",
                to="academics.subjectallocation",
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="internalexammark",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internal_marks",
                to="students.subjectenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="internalexammark",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marks",
                to="performance.internalexam",
                verbose_name="exam",
            ),
        ),
    ]
