# Generated by Django 5.2 on 2026-08-24 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="batch",
            name="unique_active_batch_per_program_year",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("program", "year"),
                name="unique_active_batch_per_program_year",
                violation_error_message="That program already has a batch for this year.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="batchsemester",
            name="unique_active_semester_per_batch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("batch", "semester"),
                name="unique_active_semester_per_batch",
                violation_error_message="That batch has already sat this semester.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="batchsemester",
            name="unique_running_semester_per_batch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False), ("status", "RUNNING")),
                fields=("batch",),
                name="unique_running_semester_per_batch",
                violation_error_message="This batch already has a semester running. Mark that one completed first.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="batchsemester",
            name="batch_semester_dates_ordered",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="batch_semester_dates_ordered",
                violation_error_message="The end date cannot fall before the start date.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="department",
            name="unique_active_department_name",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("name",),
                name="unique_active_department_name",
                violation_error_message="A department with that name already exists.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="department",
            name="unique_active_department_code",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("code",),
                name="unique_active_department_code",
                violation_error_message="A department with that code already exists.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="program",
            name="unique_active_program_code",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("code",),
                name="unique_active_program_code",
                violation_error_message="A program with that code already exists.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="program",
            name="unique_active_program_name_per_department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("department", "name"),
                name="unique_active_program_name_per_department",
                violation_error_message="That department already has a program with this name.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="program",
            name="program_total_semesters_in_range",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_semesters__gte", 1), ("total_semesters__lte", 8)
                ),
                name="program_total_semesters_in_range",
                violation_error_message="A program must run for between 1 and 8 semesters.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="subject",
            name="unique_active_subject_code_per_program_semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("program", "code", "semester"),
                name="unique_active_subject_code_per_program_semester",
                violation_error_message="That program already has a subject with this code in this semester.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="subjectallocation",
            name="unique_active_allocation_per_semester_subject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("batch_semester", "subject"),
                name="unique_active_allocation_per_semester_subject",
                violation_error_message="That subject is already allocated for this batch semester.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="teacher",
            name="unique_active_teacher_employee_code",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_archived", False),
                    models.Q(("employee_code", ""), _negated=True),
                ),
                fields=("employee_code",),
                name="unique_active_teacher_employee_code",
                violation_error_message="Another teacher already has that employee code.",
            ),
        ),
    ]
