# Generated by Django 5.2 on 2026-08-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_constraint_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                help_text="Whose authority covers everything under this department.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="academics.teacher",
                verbose_name="head of department",
            ),
        ),
    ]
