# Generated by Django 5.2 on 2026-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_historicalbatch_historicalbatchsemester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectallocation",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AddField(
            model_name="historicalsubjectallocation",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="start time"),
        ),
        migrations.AddField(
            model_name="subjectallocation",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AddField(
            model_name="subjectallocation",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="start time"),
        ),
    ]
