# Generated by Django 5.2 on 2026-09-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0007_historicalsubjectallocation_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchsemester",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semesters",
                to="academics.batch",
                verbose_name="batch",
            ),
        ),
        migrations.AlterField(
            model_name="subjectallocation",
            name="batch_semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="academics.batchsemester",
                verbose_name="batch semester",
            ),
        ),
    ]
