# Generated by Django 5.2 on 2026-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_historicalclassmeeting_classmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='graduated_on',
            field=models.DateField(blank=True, help_text='Set when the batch was marked graduated; cleared if that is undone.', null=True, verbose_name='graduated on'),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('RUNNING', 'Running'), ('GRADUATED', 'Graduated')], default='RUNNING', help_text='A graduated batch is kept out of pickers without being archived.', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='graduated_on',
            field=models.DateField(blank=True, help_text='Set when the batch was marked graduated; cleared if that is undone.', null=True, verbose_name='graduated on'),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('RUNNING', 'Running'), ('GRADUATED', 'Graduated')], default='RUNNING', help_text='A graduated batch is kept out of pickers without being archived.', max_length=20, verbose_name='status'),
        ),
    ]
