# Generated by Django 5.2 on 2026-09-10 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_academiccalendarconfiguration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendarconfiguration",
            name="show_gregorian_dates",
            field=models.BooleanField(
                default=True,
                help_text="Print the English day alongside the Bikram Sambat one in each cell.",
                verbose_name="show Gregorian dates",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendarconfiguration",
            name="theme_accent_color",
            field=models.CharField(
                default="#334155",
                help_text="Month headings and today's marker.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="accent colour",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendarconfiguration",
            name="theme_event_color",
            field=models.CharField(
                default="#0064be",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="event colour",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendarconfiguration",
            name="theme_holiday_color",
            field=models.CharField(
                default="#dc2626",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="holiday colour",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademiccalendarconfiguration",
            name="show_gregorian_dates",
            field=models.BooleanField(
                default=True,
                help_text="Print the English day alongside the Bikram Sambat one in each cell.",
                verbose_name="show Gregorian dates",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademiccalendarconfiguration",
            name="theme_accent_color",
            field=models.CharField(
                default="#334155",
                help_text="Month headings and today's marker.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="accent colour",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademiccalendarconfiguration",
            name="theme_event_color",
            field=models.CharField(
                default="#0064be",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="event colour",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademiccalendarconfiguration",
            name="theme_holiday_color",
            field=models.CharField(
                default="#dc2626",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="holiday colour",
            ),
        ),
    ]
