# Generated by Django 5.2 on 2026-09-10 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0012_academiccalendarconfiguration_show_gregorian_dates_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendarconfiguration",
            name="theme_download_band_color",
            field=models.CharField(
                default="#bf0800",
                help_text="The header band across each month of the downloaded calendar.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="download band colour",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademiccalendarconfiguration",
            name="theme_download_band_color",
            field=models.CharField(
                default="#bf0800",
                help_text="The header band across each month of the downloaded calendar.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Give the colour as a six-digit hex value, for example #1d4ed8.",
                        regex="^#(?:[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="download band colour",
            ),
        ),
    ]
